"""Generate MAX's concrete fusion registrations from one struct template.

MAX 26.5 drops parent-struct parameters when lowering ElementwiseUnaryOp and
ElementwiseUnaryMixedOp calls. Keep the maintained implementation generic,
then register concrete forwarders that the graph compiler can fuse.

Run ``uv run python scripts/generate_elementwise_ops.py`` after adding a kind
in custom_mojo_ops.elementwise, or pass ``--check`` to verify the checked-in file.
"""

import argparse
import ast
from pathlib import Path
from typing import cast

ROOT = Path(__file__).resolve().parents[1]
OUTPUT = ROOT / "torch_mojo_backend/mojo_kernels/elementwise_generated.mojo"
HEADER = """# Generated by scripts/generate_elementwise_ops.py. Do not edit by hand.
# MAX 26.5 needs concrete structs for fusion; all implementations share
# ElementwiseOp[kind] and the native backend's SIMD math.

import extensibility
from extensibility import ElementwiseUnaryMixedOp

from .elementwise import ElementwiseOp
"""
TEMPLATE = """

@extensibility.register("elementwise_{kind}")
struct {name}(ElementwiseUnaryMixedOp):
    @staticmethod
    def elementwise[
        dtype: DType,
        out_dtype: DType,
        width: SIMDLength,
    ](x: SIMD[dtype, width]) -> SIMD[out_dtype, width]:
        comptime Op = ElementwiseOp["{kind}"]
        return Op.elementwise[dtype, out_dtype, width](x)
"""


def render() -> str:
    """Read the public helper's kind annotation without importing the backend."""
    source = ROOT / "torch_mojo_backend/custom_mojo_ops.py"
    module = ast.parse(source.read_text())
    function = next(
        node
        for node in module.body
        if isinstance(node, ast.FunctionDef) and node.name == "elementwise"
    )
    annotation = next(arg.annotation for arg in function.args.args if arg.arg == "kind")
    if not isinstance(annotation, ast.Subscript):
        raise ValueError("elementwise.kind must have a Literal annotation")
    kinds = ast.literal_eval(annotation.slice)
    if not isinstance(kinds, tuple) or not all(isinstance(kind, str) for kind in kinds):
        raise ValueError("elementwise.kind must be a Literal of strings")
    return HEADER + "".join(
        TEMPLATE.format(
            kind=kind,
            name="Elementwise" + "".join(part.capitalize() for part in kind.split("_")),
        )
        for kind in cast(tuple[str, ...], kinds)
    )


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    expected = render()
    if args.check:
        if not OUTPUT.exists() or OUTPUT.read_text() != expected:
            print("Regenerate with uv run python scripts/generate_elementwise_ops.py")
            return 1
    else:
        OUTPUT.write_text(expected)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
