# This workflows will upload a Python Package to Pypi when a release is created on the Github UI

name: Upload Python Package

on:
  release:
    types: [created]

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: pypi
    permissions:
      id-token: write
    steps:
    - uses: actions/checkout@v2
    - name: Install uv
      uses: astral-sh/setup-uv@v7
    - name: Build wheels
      run: uv build
    - name: Publish package distributions to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
    - name: Testing the uploaded wheel
      run: |
        uv run --with torch-mojo-backend --no-project -- python -c "import torch_mojo_backend"
